name: "RPi Camera Streamer (Full Access)"
version: "1.1.0"
panel_icon: "mdi:cctv"
panel_title: RPi Camera Streamer
slug: "rpi-camera-streamer"
description: "Universal CSI/USB camera streamer, optimized for RPi 5 and all official camera modules."
url: "https://github.com/Brawndo-Corp/rpi-camera-haos-app"
startup: application
boot: auto
init: false
full_access: true
protected: false  
host_network: true
host_ipc: true
video: true
udev: true
devices:
  - /dev/dma_heap:/dev/dma_heap
  - /dev/dma_heap/system:/dev/dma_heap/system
  - /dev/dma_heap/linux,cma:/dev/dma_heap/linux,cma
  - /dev/v4l-subdev0:/dev/v4l-subdev0
  - /dev/v4l-subdev1:/dev/v4l-subdev1
  - /dev/v4l-subdev2:/dev/v4l-subdev2
  - /dev/media0:/dev/media0
  - /dev/media1:/dev/media1
  - /dev/media2:/dev/media2
  - /dev/media3:/dev/media3
options:
  camera_path: "0"
  resolution: "1456x1088"
  framerate: 15
  bitrate: 12000000
  h264_profile: "main"
privileged:
  - PERFMON
  - SYS_RAWIO
schema:
  camera_path: str
  resolution: list(4056x3040|2028x1520|1920x1080|1456x1088|1280x720)
  framerate: int
  bitrate: int
  h264_profile: list(baseline|main|high)
arch:
  - aarch64
